# Header
menu:
  Home: /
  Archives: /archives
  About: https://xianzhaoduan.com
  # Github:
  #   url: https://github.com/PaulDuanGitHub/blog
  #   icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Paul Duan's Blog

# URL of the Home page image
index_cover: img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: 'G-KNPEXFEH64'

# Addthis ID
addthis:

# set your own favicon
favicon: /blog/img/favicon.ico

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/PaulDuanGitHub/blog
gitlab_url:
linkedin_url:
mailto: